name: Test Workflow

on:
  push:
    branches: ["main", "backendlynew"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show uname
        run: echo "Workflow is running on $(uname -a)"

      - name: List backend files
        run: ls -la backend || true
